# created by eselect-repo

[guru]
location = /var/db/repos/guru
sync-type = git
sync-uri = https://github.com/gentoo-mirror/guru.git

[zGentoo]
location = /var/db/repos/zGentoo
sync-type = git
sync-uri = https://lab.simple-co.de/zappel/zGentoo.git

[hyproverlay]
location = /var/db/repos/hyproverlay
sync-type = git
sync-uri = https://codeberg.org/hyproverlay/hyproverlay.git

[supertux88]
location = /var/db/repos/supertux88
sync-type = git
sync-uri = https://github.com/SuperTux88/gentoo-overlay.git
